### PR TITLE
Add watch task.

### PR DESCRIPTION
**Pull request by denysdovhan**
I think it's very useful thing.

### CODE REVIEW

**Comment by iamstarkov** [comment]
I used to have `transpile:dev` and you?

**Comment by denysdovhan** [comment]
Usualy I use `watch` task.
BTW: [Rise](git.io/rise) uses this thask too istead of `dev` or whatever.

**Comment by iamstarkov** [comment]
can you rebase pull-request? i merged prev one, so now we have conflicts

**Comment by iamstarkov** [comment]
watch is also good name, can you rebase branch, I will merge it

**Comment by denysdovhan** [comment]
of course, wait for a while

**Comment by denysdovhan** [comment]
sorry, I'm stupid. accidentally I merged it with master.
Now all right.

**Comment by iamstarkov** [comment]
merged

**Comment by iamstarkov** [comment]
maybe I have some good insights about coverage also

**Comment by denysdovhan** [comment]
:+1:

**Comment by denysdovhan** [comment]
>  I have some good insights about coverage

What do you mean?

**Comment by iamstarkov** [comment]
take a look http://onsen.io/blog/mocha-chaijs-unit-test-coverage-es6/

**Comment by iamstarkov** [comment]
it should work

**Comment by denysdovhan** [comment]
it seems I've already tried it

**Comment by iamstarkov** [comment]
didnt work?

**Comment by iamstarkov** [comment]
it looks like you suggested in coverage pull-request except of switching `--require to `--compilers`. maybe its the case

**Comment by denysdovhan** [comment]
Maybe, not sure.

**Pull request merged**
