### PR TITLE
Fix broken coverage.

### PR DESCRIPTION
**Pull request by denysdovhan**
Just fix broken coverage.

### CODE REVIEW

**Comment by iamstarkov** [comment]
can you show projects with this coverage script working properly?

**Comment by denysdovhan** [comment]
Sure https://github.com/denysdovhan/mdast-typographer 
It doesn't work perfect, but it works.

**Comment by iamstarkov** [comment]
Thank you

**Comment by iamstarkov** [comment]
unfortunately i’m still getting `No coverage information was collected, exit without writing coverage information`

**Comment by iamstarkov** [comment]
here we go

**Comment by iamstarkov** [comment]
coverage is not working with mdast-typographer neither
```
➜  mdast-typographer git:(master) npm run coverage

> mdast-typographer@0.2.0 coverage /Users/vlasta/projects/mdast-typographer
> babel-node ./node_modules/.bin/isparta cover _mocha index.js -- --require babel-core/register



  mdast-typographer
    ✓ should transform (48ms)
    ✓ should remove disabled transformers
    ✓ should remove all transformers
    ✓ should load locale
    ✓ should use after transformers
    ✓ should use before transformers
    ✓ should use after and before transformers


  7 passing (99ms)

No coverage information was collected, exit without writing coverage information
```

**Comment by iamstarkov** [comment]
so its coverage is broken, on the other hand its exactly in the same state as before

**Comment by denysdovhan** [comment]
WTF?
It was working for me.

**Comment by iamstarkov** [comment]
maybe its my bad
```
➜  mdast-typographer git:(master) node -v && npm -v
v0.10.40
1.4.28
```

**Comment by iamstarkov** [comment]
but its not
```
➜  mdast-typographer git:(master) n latest
➜  mdast-typographer git:(master) node -v && npm -v
v5.1.0
3.3.12
➜  mdast-typographer git:(master) npm run coverage

> mdast-typographer@0.2.0 coverage /Users/vlasta/projects/mdast-typographer
> babel-node ./node_modules/.bin/isparta cover _mocha index.js -- --require babel-core/register



  mdast-typographer
    ✓ should transform (74ms)
    ✓ should remove disabled transformers
    ✓ should remove all transformers
    ✓ should load locale
    ✓ should use after transformers
    ✓ should use before transformers
    ✓ should use after and before transformers


  7 passing (148ms)

No coverage information was collected, exit without writing coverage information
```

**Comment by denysdovhan** [comment]
Nope. Not sure.

**Comment by iamstarkov** [comment]
i got it working here https://github.com/iamstarkov/some8/commit/620c46fd8625733ef2d2ff8e0e97757976771b3f

**Comment by iamstarkov** [comment]
screen shot 2015-11-24 at 19 33 49

**Comment by iamstarkov** [comment]
fixed and published as v1.1.8

**Comment by denysdovhan** [comment]
Win 👍

**Pull request merged**
