### PR TITLE
Add ESLint

### PR DESCRIPTION
**Pull request by kinday**
This PR adds basic ESLint set up support.

At the end of the day I came to conclusion separate ESLint generator would be a better solution. Since I can’t guarantee it would be done in short terms I make this pull request.

### CODE REVIEW

**Comment by iamstarkov** [comment]
what do you think about eslint airbnb preset?

**Comment by kinday** [comment]
I use it in most of my projects with some minor tweaks.

**Comment by iamstarkov** [comment]
can you show me your tweaks?

**Comment by kinday** [comment]
They vary from project to project. Common one is `"object-curly-spacing": [2, "always"]`. When I use `immutable` I add its primitives to `new-cap` ignores. Sometimes I add some specific `globals`.

**Comment by iamstarkov** [comment]
I also use airbnb config. what do you think about sticking to airbnb config?

**Comment by kinday** [comment]
I can set is as a default instead of ESLint recommended but keep alternatives as well. Guess there must also be a possibility to choose no preset.

**Comment by iamstarkov** [comment]
maybe just ask one question? "do you like eslint and its airbnb config?" if so, just add it, if not. just keep it as it is now

**Comment by kinday** [comment]
Sounds redundant. “Do you like ESLint...” is similar to “Use ESLint” and “...its airbnb config” is similar to later choice with `airbnb` as default.

Let’s keep it as is except I’ll set default value to `airbnb`.

**Comment by iamstarkov** [comment]
i have something for you у меня тоже для тебя что-то есть https://github.com/iamstarkov/generator-eslint-init

**Pull request closed without merging**
